name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install axios

      - name: Perform code review and post results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          node <<EOF
          const axios = require('axios');

          const githubToken = process.env.GITHUB_TOKEN;
          const geminiApiKey = process.env.GEMINI_API_KEY;
          const repository = process.env.GITHUB_REPOSITORY;
          const pullRequestNumber = process.env.GITHUB_PULL_REQUEST;

          const githubApiUrl = `https://api.github.com/repos/${repository}/pulls/${pullRequestNumber}/files`;
          const geminiApiUrl = 'https://generativelanguage.googleapis.com/v1beta/chat/completions';

          const headers = {
              Authorization: `Bearer ${githubToken}`,
              'Content-Type': 'application/json',
          };

          async function fetchChangedFiles() {
              const response = await axios.get(githubApiUrl, { headers });
              return response.data; // 変更されたファイルリスト
          }

          async function reviewCode(diff) {
              const geminiHeaders = {
                  Authorization: `Bearer ${geminiApiKey}`,
                  'Content-Type': 'application/json',
              };

              const data = {
                  model: 'gemini-1.5-flash',
                  messages: [
                      { role: 'system', content: 'あなたは優秀なコードレビュアーです。' },
                      { role: 'user', content: `以下のコード差分をレビューしてください:\n\n${diff}` },
                  ],
              };

              const response = await axios.post(geminiApiUrl, data, { headers: geminiHeaders });
              return response.data.choices[0].message.content; // レビューコメント
          }

          async function postReviewComment(file, line, comment) {
              const reviewUrl = `https://api.github.com/repos/${repository}/pulls/${pullRequestNumber}/comments`;

              const payload = {
                  body: comment,
                  path: file,
                  line: line,
                  side: 'RIGHT', // 変更後のコードにコメントする
              };

              await axios.post(reviewUrl, payload, { headers });
          }

          async function main() {
              const changedFiles = await fetchChangedFiles();

              for (const file of changedFiles) {
                  const { filename, patch } = file;

                  const lines = patch.split('\n');
                  for (let i = 0; i < lines.length; i++) {
                      if (lines[i].startsWith('+') && !lines[i].startsWith('+++')) {
                          const lineContent = lines[i].substring(1);
                          const reviewComment = await reviewCode(lineContent);

                          await postReviewComment(filename, i + 1, reviewComment);
                      }
                  }
              }

              console.log('レビューコメントをPRに追加しました');
          }

          main().catch(error => {
              console.error('エラー:', error.response ? error.response.data : error.message);
          });
          EOF
